language: scala
sudo: required
dist: trusty

scala:
- 2.10.6
- 2.11.11

cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

env:
  global:
  - PUBLISH_ARTIFACT: false
  - CASSANDRA_VERSION: 3.11.3
  - TARGET_SCALA_VERSION: "2.12.8"
  - CASSANDRA_NODES: 1
  - GH_REF: github.com/outworkers/phantom-pro.git
  - secure: qUNp6pM5m8HfbiviFDTJ9ZVoudqTjhiVSceaY5b1iQsT8bd6JAZByc8G4culBEVsdXIoozyiHQRlcp42yQKaIdtOmssnXyT+/FZ1FSwGHeFGPQ/aHP2V8hpTtpYVymUYiZepxjNGTvW6HtFeu77te+zMp4KchaPmDgx2jbWk7T3UFktrhm+sCbt+LNdTqZ9jzyTJKxMdypWQd5DX+hy5RGPNzamk6jqEPapWbhKVpZvGgIAJJDJ6uY7CwBEHjtd9Yik8wvKDM/ONKZiHc3/Y/BTFPBotheHHzg0lQ3wOg9VoK697mhbNZ/MT/SBH1rBaLesS453TSf4P3H/oRn5L5l8WV9oFFfdHOpSRBGdYx6rp8mxNVqHA2UJe+QM/GO0NVOxQ0Ih6/xH7SOelCEhjneE5D0Kq/32J9tJXmLcGP8LCr3pOzMvkCc2RkTdZu63JLpRWvuzbgHchNzJc+NIaAFRFb4uSWDfA9iXP93GRDrAkaNY5jWB0WLSkUyogzJEhzjU8Pwu4gt1vrd7l5tRo29pZ3gQJ3jV2iLExN8yRBur2m/ih3T9vWJjBruuv3RueU42ogb0u5Ut4jsc16TTh3Z9fiZuquX79Twa3aY6kDXZ9Mwdjt0MW2RN4o1c821vl+w7kUQNgNLrEriaOmsh7TwbI351jEUKfHjafWaAllPw=
  - secure: ym/I7XQEc3/g4LHMUnZfSXPhfVq44iBFpWMk9V74yJoUjLuMdOmxYb7Vg0AxGdlnwBRm8hpHYr7ZpN1bEWZWob6wJSE+T4bIh3X3PpjSV79MRTiGPhqioLtVyQRvTpfHPL75PTD+RFYjBKgN7IHS7pIU6ykQsANDCwZuYp1jDZODFm27W+soWlveoGgSRpz0WVE+J8hoeS4PtpwErIMpMGJAliyVZvysUp204cQbHktDxq9Fj15kP7/FObjSyRDiO7w5+i13Pi+0k+P2bJyo6KmQmv5hEtO6zUG33OnWYGhObK4S/Qpc2d0gOxgsPFkdSTZ2mzyNAYTDNZBtUO46xjTCChOeiUlH25OwEiFr0RfGujnqjWG94KvybWLdAl+h4xD7X3vTmQJ3vfhZ7MieivDGoGpiiBQHU3K8Au4PXGbVOEXE+MkmiQCVu9StdvylVesMThqi5SlIqgf5pgWfeVEWayRWmCX8SuniKlXLAfnYOtBmD0wnH0PoH3ZV4z/Z/2p6s9uUZdd9HAZ3A4dfpjjCsu038nn+jaqJWg8USIka+Kp37ao2l4xpz+XzBnBOaKIfxTT5z1AHHjLV+dO3XYfAbhVkhlTBrDiEOm2SxR3+7KLlBAMWAAcbSBBP3eM0lFUdssf2ZnwJeLymWNBRT15/K67UpGHMLgv4VVPMu6I=
  - secure: rhQFrDFqhCfb7CNHdSj816c4V9FJDnxM4tqQPWaDQMHTQ1ETvu78kbMxZ8qW6R39E1NsnAN6uld4BQ4an01LtvhK8whHee8mfJUrWETss2y9YEYeMeE2ZfsDNrPxijZzF9RxQeY+lxz4ujp4y0KRC1Rwgj15Wl8ieuYuLGHqb/iTUF65XvKYqkIqFLddVkTCD2lnCLv2P9agxjV+Ivm/OCdghW8KeZaLOTyoYpzDGM4PZSehsaIQa1ePB8UnI+X1UoPr5YYjV1icIFQoLprJXcw49h54EcBLGZZ3Sn+aW9clQdXMR3IJSgfnF5n1QR9Q72gdAIDhh3nYCRjnCyTsbcl7j2JB7r6WjVSisii2NsTBXmGjLd3IesDE48S0TD7WdIXIBDLWmeu2NmXtfA3yYj9/CA6UfymnoDwLsEhglILNvAEMjESdAlXrVzK0NSfrEPfycEwVvKT9cNqwHfsacYyDfMKknBtrA2fYWhHzPFygFk9V46zkD6du5u1x5W8nsgvyFCHdAdOHHzYsbd7A3JRC+sVAeZidGsfAvV1jaen6Nei/r05cxOx2rCFN8TWH+8HM6iNcPQKEeKHmFesJLxrw/kRF4Xj/y1y0t1+YiW+sr49mdexU/3dUG2ZwPcjLzNDN43N9Ro34yatxwVVu+j4cHSh0L/671oilii2jHYQ=
notifications:
  slack:
  - websudos:P9QNXx1ZGFnDHp3v3jUqtB8k
  email:
  - dev@outworkers.com
branches:
  only:
  - master
  - develop
jdk:
- oraclejdk8

install:
  - ./build/cassandra.sh

matrix:
  include:
  - scala: 2.12.8
    jdk: oraclejdk8
  - scala: 2.12.8
    jdk: oraclejdk8
    env: CASSANDRA_VERSION=3.11.3 PUBLISH_ARTIFACT=true
  - scala: 2.12.8
    jdk: oraclejdk8
    env: CASSANDRA_VERSION=3.0.17
  - scala: 2.11.12
    jdk: oraclejdk8
    env: CASSANDRA_VERSION=2.2.9

addons:
  apt:
    packages:
    - oracle-java8-installer
before_install: unset SBT_OPTS JVM_OPTS
before_script: travis_retry sbt "plz $TRAVIS_SCALA_VERSION update"

script: ./build/build.sh
