env:
  - CODACY_PROJECT_TOKEN = 8bf59048f5d145d1885c0ab105f11ce3


language: scala
sudo: false
services:
- cassandra
scala:
- 2.10.6
- 2.11.8
env:
  global:
  - GH_REF: github.com/outworkers/phantom-pro.git
notifications:
  slack:
  - websudos:P9QNXx1ZGFnDHp3v3jUqtB8k
  email:
  - dev@websudos.co.uk
branches:
  only:
  - master
  - develop
jdk:
- oraclejdk7
- oraclejdk8

before_script: travis_retry sbt ++$TRAVIS_SCALA_VERSION update
script: ./build/run_tests.sh
after_success: ./build/publish.sh
